name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1    
    - name: Run Buildx
      run: |
        echo ${{secrets.hub_pass}} | docker login -u ${{secrets.hub_name}} --password-stdin
        docker buildx build \
            -t mq83/gitea \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            . \
            --push
