name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1    
    - name: Run Buildx
      run: |
        docker login -u ${{secrets.hub_name}} -p ${{secrets.hub_pass}}
        docker buildx build \
            -t mq83/gitea \
            --platform linux/386,linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64,linux/ppc64le \
            . \
            --push
